"""New migration

Revision ID: c4e2b4ba7dff
Revises: cdb0b12ad790
Create Date: 2024-12-21 11:17:50.265483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e2b4ba7dff'
down_revision: Union[str, None] = 'cdb0b12ad790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_foreign_key(None, 'games', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_column('games', 'user_id')
    # ### end Alembic commands ###
